name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "albanisyahril123@gmail.com"
          git config --global user.name "albanisyahril"
      - name: Add remote 
        env:
          HG: ${{ secrets.HG }}
        run: git remote set-url origin https://$HG@huggingface.co/spaces/albanisyahril/demo-trash-classification
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install
      - name: Push to hub
        env:
          HG: ${{ secrets.HG }}
        run: |
          git lfs track "*.h5" "*.keras"
          git add Deploy/Model/model.h5
          git add Deploy/Model/model.keras
          git commit -m "Track large files with Git LFS"
          git push --force "https://albanisyahril:${HG}@huggingface.co/spaces/albanisyahril/demo-trash-classification" main
